executors:
  openjdk-executor:
    docker:
      - image: 'cimg/openjdk:17.0.0'
orbs:
  gradle: circleci/gradle@2.2.0
version: 2.1

jobs:
  build_test:
    executor:
      openjdk-executor

    steps:
      - checkout

      - run:
          name: Run tests and create Jacoco Report
          command: ./gradlew jacocoTestReport

      - run:
          name: Analyze on SonarCloud
          command: ./gradlew sonarqube

      - persist_to_workspace:
          root: .
          paths:
            - build/*
            - cardmarket-api/build/*
            - cardmarket-client/build/*
            - cardmarket-core/build/*
            - cardmarket-rest/build/*
            - login-api/build/*
            - login-core/build/*
            - .gradle/*


  deploy:
    executor:
      openjdk-executor

    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "11:55:85:8e:fb:0f:2b:34:10:e1:e4:c7:ea:de:47:16"
      - run:
          name: Add host to known_hosts
          command: |
            echo $HOST_SIGNATURE >> ~/.ssh/known_hosts
      - run:
          name: Copy secrets
          command: scp -P $SSH_PORT $SSH_USER@$SSH_HOST:~/cardmarket/*.yaml cardmarket-rest/src/main/resources/
      - run:
          name: Build projects
          command: ./gradlew build
      - run:
          name: Copy jar
          command: scp -P $SSH_PORT cardmarket-rest/build/libs/cardmarket-rest-0.0.1-SNAPSHOT.jar $SSH_USER@$SSH_HOST:~/cardmarket
      - run:
          name: Stop previous processes
          command: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "./cardmarket/kill_prev_process.sh"
      - run:
          name: Deploy Over SSH
          command: |
            ssh -fn -p $SSH_PORT $SSH_USER@$SSH_HOST "./cardmarket/deploy_back.sh cardmarket-rest-0.0.1-SNAPSHOT.jar"


workflows:
  test_and_publish:
    jobs:
      - build_test:
          context: SonarCloud
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only: master
