spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/login-service
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    database: POSTGRESQL
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate:
      jdbc.time_zone: UTC
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
  sql:
    init:
      platform: postgres
server:
  port: 8081
  error:
    include-message: always

springdoc:
  show-login-endpoint: true

client:
  host: https://api.cardmarket.com/ws/v2.0/output.json/

  oauth:
    signature: HMAC-SHA1
    version: 1.0

price:
  prices-to-keep: 2
  change-price-threshold: 1.3
  too-high-price-threshold: 2.0

