spring:
  datasource:
    username: postgres
    password: postgres

security:
  jwt:
    token:
      expire-length: 1800000
  allowed-origins: http://localhost:3000

schedule:
  update-prices: 0 0 0 1 1 0