spring:
  datasource:
    username: pi
    password: kaRvvmDJpqu8DzHvrLBJCtMjy8B3uU

security:
  jwt:
    token:
      expire-length: 18000
  allowed-origins: https://cardmarket.happyharbor.io

server:
  servlet:
    context-path: /api

schedule:
  update-prices: 0 0 5 * * *